# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AlterField(
            model_name='school',
            name='composite_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
