# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170428_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite_id', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=200)),
                ('school_id', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.District')),
            ],
        ),
    ]
