# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170428_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleNineGap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=15)),
                ('gap', models.FloatField(null=True)),
                ('real_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.NewSchool')),
            ],
        ),
    ]
