# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_titleninegap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='composite_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
