# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_newschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeenrollment',
            name='real_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.NewSchool'),
        ),
        migrations.AddField(
            model_name='sportsenrollment',
            name='real_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.NewSchool'),
        ),
        # migrations.AddField(
        #     model_name='titleninegap',
        #     name='real_school',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.NewSchool'),
        # ),
    ]
